[project]
name = "pixi-repro"
version = "0.1.0"
description = "Add a short description here"
authors = ["Ben Moss <bmoss40@bloomberg.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64", "linux-aarch64"]

[tasks]

[dependencies]
pytest = ">=6.2,<7.0"

[pypi-dependencies]
python-git = ">= 3.1.43"

